---
- name: install docker-py workaround
  pip: name=docker-py

- name: start webserver container
  docker:
    name: "{{ webserver_container_name }}"
    image: szeist/phalcon-apache2
    state: started
    ports:
      - "80:80"
    volumes:
      - "{{ local_web_folder }}:/deploy"
      - "{{ nginx_config_folder}}:/etc/nginx/sites-enabled"
    env: "{{env_vars}}"
